export type Category = "FMCG" | "Furniture" | "Medical Equipment" | "Electronics";

export type Product = {
  slug: string;
  name: string;
  brand: string;
  /** Broad sourcing vertical (drives the catalog filters). */
  category: Category;
  /** Finer label shown on the card chip (e.g. "Chocolate", "Ergonomic Seating"). */
  subcategory: string;
  origin: string;
  originFlag: string;
  moq: string;
  leadTime: string;
  blurb: string;
  description: string;
  highlights: string[];
  accent: string;
  certifications: string[];
  containerLoad: string;
};

export const products: Product[] = [
  // ──────────────────────────────── FMCG ────────────────────────────────
  {
    slug: "lindt-excellence-70",
    name: "Lindt Excellence 70% Dark 100g",
    brand: "Lindt",
    category: "FMCG",
    subcategory: "Chocolate",
    origin: "Switzerland",
    originFlag: "🇨🇭",
    moq: "30 cases",
    leadTime: "2–3 weeks",
    blurb: "Premium Swiss dark chocolate with deep cocoa intensity.",
    description:
      "Lindt Excellence 70% Cocoa delivers an intense yet smooth dark chocolate experience from the master Swiss chocolatiers. A premium gifting and self-treat staple with year-round demand and strong margins across modern trade.",
    highlights: ["Master Swiss chocolatier craft", "70% cocoa intensity", "Premium gifting positioning"],
    accent: "#7b4b27",
    certifications: ["UTZ Cocoa"],
    containerLoad: "2,100 cases / 20ft",
  },
  {
    slug: "barilla-spaghetti-n5",
    name: "Barilla Spaghetti No.5 500g",
    brand: "Barilla",
    category: "FMCG",
    subcategory: "Pasta & Grains",
    origin: "Italy",
    originFlag: "🇮🇹",
    moq: "40 cases",
    leadTime: "2–3 weeks",
    blurb: "Italy's #1 durum wheat semolina spaghetti, the global pantry standard.",
    description:
      "Barilla Spaghetti No.5 is the world's most recognized pasta, made from 100% premium durum wheat semolina with the perfect al dente bite. A high-rotation pantry essential with universal demand and dependable container economics.",
    highlights: ["100% durum wheat semolina", "World's #1 pasta brand", "High-rotation staple SKU"],
    accent: "#1a4f9c",
    certifications: ["Non-GMO", "ISO 22000"],
    containerLoad: "1,560 cases / 20ft",
  },
  {
    slug: "oreo-original-154",
    name: "Oreo Original Sandwich Cookies 154g",
    brand: "Oreo",
    category: "FMCG",
    subcategory: "Snacks",
    origin: "United States",
    originFlag: "🇺🇸",
    moq: "40 cases",
    leadTime: "3 weeks",
    blurb: "The world's best-selling cookie: cocoa wafers with vanilla creme.",
    description:
      "Oreo is the planet's favorite cookie: two crisp cocoa wafers hugging a sweet vanilla creme. A universally demanded snack SKU with relentless shelf rotation and broad multi-channel distribution.",
    highlights: ["World's best-selling cookie", "Universal demand", "Multi-channel rotation"],
    accent: "#1a2b6b",
    certifications: ["RSPO Palm Oil"],
    containerLoad: "2,200 cases / 20ft",
  },
  {
    slug: "haribo-goldbears",
    name: "Haribo Goldbears 200g",
    brand: "Haribo",
    category: "FMCG",
    subcategory: "Confectionery",
    origin: "Germany",
    originFlag: "🇩🇪",
    moq: "35 cases",
    leadTime: "3 weeks",
    blurb: "The original gummy bear with five fruity flavors since 1922.",
    description:
      "Haribo Goldbears are the original gummy bears that started it all, with five classic fruit flavors and unmistakable chewy texture. A confectionery cornerstone with cross-generational appeal and very high turnover.",
    highlights: ["The original gummy bear", "Five classic fruit flavors", "Very high turnover SKU"],
    accent: "#e1a100",
    certifications: ["Halal (select lines)"],
    containerLoad: "2,600 cases / 20ft",
  },
  {
    slug: "twinings-earl-grey",
    name: "Twinings Earl Grey 100 Tea Bags",
    brand: "Twinings",
    category: "FMCG",
    subcategory: "Beverages",
    origin: "United Kingdom",
    originFlag: "🇬🇧",
    moq: "25 cases",
    leadTime: "3 weeks",
    blurb: "Classic British bergamot-scented black tea since 1706.",
    description:
      "Twinings Earl Grey blends fine black teas with the distinctive citrus aroma of bergamot, a recipe refined over three centuries. A pantry staple with loyal global following and dependable repeat purchase.",
    highlights: ["Bergamot-scented black tea", "Heritage brand since 1706", "Loyal repeat purchase base"],
    accent: "#1f5f3f",
    certifications: ["Rainforest Alliance"],
    containerLoad: "1,800 cases / 20ft",
  },

  // ─────────────────────────────── Furniture ───────────────────────────────
  {
    slug: "ikea-billy-bookcase",
    name: "IKEA BILLY Bookcase System",
    brand: "IKEA",
    category: "Furniture",
    subcategory: "Flat-pack Living",
    origin: "Sweden",
    originFlag: "🇸🇪",
    moq: "1 × 40ft container",
    leadTime: "5–7 weeks",
    blurb: "The world's best-selling flat-pack bookcase, engineered for dense container loading.",
    description:
      "IKEA's BILLY is the definitive flat-pack bookcase — democratic design that ships compact and assembles fast. Flat packing makes it exceptionally container-efficient, ideal for retailers and project fit-outs sourcing volume from Northern Europe.",
    highlights: ["Iconic flat-pack efficiency", "High cube utilization", "FSC-certified board"],
    accent: "#0058a3",
    certifications: ["FSC", "ISO 9001"],
    containerLoad: "Up to 600 units / 40ft",
  },
  {
    slug: "herman-miller-aeron",
    name: "Herman Miller Aeron Ergonomic Chair",
    brand: "Herman Miller",
    category: "Furniture",
    subcategory: "Ergonomic Seating",
    origin: "United States",
    originFlag: "🇺🇸",
    moq: "25 units",
    leadTime: "6–8 weeks",
    blurb: "The benchmark ergonomic task chair for premium offices worldwide.",
    description:
      "The Aeron set the global standard for ergonomic seating, with its breathable Pellicle suspension and posture-adaptive support. A flagship specification for corporate, co-working and executive fit-outs commanding strong resale and brand equity.",
    highlights: ["Industry-benchmark ergonomics", "12-year warranty class", "Premium corporate spec"],
    accent: "#b23a48",
    certifications: ["BIFMA", "GREENGUARD Gold"],
    containerLoad: "180 units / 40ft",
  },
  {
    slug: "vitra-eames-dsw",
    name: "Vitra Eames Plastic Chair DSW",
    brand: "Vitra",
    category: "Furniture",
    subcategory: "Design Furniture",
    origin: "Switzerland",
    originFlag: "🇨🇭",
    moq: "30 units",
    leadTime: "5–7 weeks",
    blurb: "Authentic licensed Eames design furniture from Switzerland's Vitra.",
    description:
      "Vitra produces the authentic, licensed Eames Plastic Chair collection — a design icon bridging residential, hospitality and contract interiors. A high-margin statement piece with enduring demand across design-led retail and HoReCa.",
    highlights: ["Authentic licensed design", "Cross-segment appeal", "High-margin statement SKU"],
    accent: "#d2232a",
    certifications: ["ISO 14001", "Cradle to Cradle (select lines)"],
    containerLoad: "320 units / 40ft",
  },
  {
    slug: "natuzzi-editions-sofa",
    name: "Natuzzi Editions Leather Sofa",
    brand: "Natuzzi",
    category: "Furniture",
    subcategory: "Sofas & Upholstery",
    origin: "Italy",
    originFlag: "🇮🇹",
    moq: "10 units",
    leadTime: "8–10 weeks",
    blurb: "Italian-designed leather upholstery, a global premium living-room name.",
    description:
      "Natuzzi Editions brings Italian design heritage to full-grain leather seating built for the premium living-room category. A recognized export brand with strong showroom pull and dependable demand across modern furniture retail.",
    highlights: ["Italian design heritage", "Full-grain leather", "Premium showroom pull"],
    accent: "#8c6a4a",
    certifications: ["ISO 9001", "Leather Working Group"],
    containerLoad: "40 units / 40ft",
  },
  {
    slug: "steelcase-series-1",
    name: "Steelcase Series 1 Task Chair",
    brand: "Steelcase",
    category: "Furniture",
    subcategory: "Office Systems",
    origin: "United States",
    originFlag: "🇺🇸",
    moq: "30 units",
    leadTime: "6–8 weeks",
    blurb: "Value-engineered ergonomic seating for large office roll-outs.",
    description:
      "Steelcase Series 1 delivers proportioned ergonomic support at a roll-out-friendly price, engineered for fleet office procurement. A workhorse contract SKU favored by facilities buyers fitting out at scale.",
    highlights: ["Fleet-friendly value", "Proven contract durability", "Fast roll-out logistics"],
    accent: "#5b4b8a",
    certifications: ["BIFMA", "GREENGUARD"],
    containerLoad: "200 units / 40ft",
  },

  // ─────────────────────────── Medical Equipment ───────────────────────────
  {
    slug: "philips-intellivue-monitor",
    name: "Philips IntelliVue Patient Monitor",
    brand: "Philips Healthcare",
    category: "Medical Equipment",
    subcategory: "Patient Monitoring",
    origin: "Netherlands",
    originFlag: "🇳🇱",
    moq: "5 units",
    leadTime: "8–12 weeks",
    blurb: "Hospital-grade multiparameter patient monitoring from Philips.",
    description:
      "Philips IntelliVue monitors deliver continuous multiparameter vitals for ICU, OR and acute-care settings, with clinically validated measurement and networked data. A core capital-equipment line for hospital procurement and tender supply.",
    highlights: ["ICU/OR grade monitoring", "Networked vitals data", "Hospital tender ready"],
    accent: "#0b3b8c",
    certifications: ["CE (MDR)", "ISO 13485", "FDA 510(k)"],
    containerLoad: "Palletized, LCL/FCL",
  },
  {
    slug: "siemens-healthineers-mri",
    name: "Siemens Healthineers MAGNETOM MRI",
    brand: "Siemens Healthineers",
    category: "Medical Equipment",
    subcategory: "Diagnostic Imaging",
    origin: "Germany",
    originFlag: "🇩🇪",
    moq: "1 unit",
    leadTime: "16–24 weeks",
    blurb: "Advanced MRI imaging systems for diagnostic and research centers.",
    description:
      "Siemens Healthineers MAGNETOM MRI platforms set a global benchmark in diagnostic imaging, combining image quality with workflow automation. A high-value capital project requiring coordinated freight, rigging and installation logistics.",
    highlights: ["Benchmark image quality", "Project freight & rigging", "Diagnostic & research grade"],
    accent: "#00b3a4",
    certifications: ["CE (MDR)", "ISO 13485", "FDA"],
    containerLoad: "Project cargo / break-bulk",
  },
  {
    slug: "ge-healthcare-vivid-ultrasound",
    name: "GE HealthCare Vivid Ultrasound",
    brand: "GE HealthCare",
    category: "Medical Equipment",
    subcategory: "Ultrasound",
    origin: "United States",
    originFlag: "🇺🇸",
    moq: "3 units",
    leadTime: "10–14 weeks",
    blurb: "Cardiovascular and general-imaging ultrasound systems.",
    description:
      "GE HealthCare's Vivid ultrasound range covers cardiovascular and general diagnostic imaging with portable and cart-based options. A versatile diagnostic SKU with broad demand across hospitals, clinics and mobile screening programs.",
    highlights: ["Cardiac & general imaging", "Portable + cart options", "Broad clinical demand"],
    accent: "#3b3b98",
    certifications: ["CE (MDR)", "ISO 13485", "FDA 510(k)"],
    containerLoad: "Palletized, LCL/FCL",
  },
  {
    slug: "drager-icu-ventilator",
    name: "Dräger ICU Ventilator System",
    brand: "Dräger",
    category: "Medical Equipment",
    subcategory: "Anesthesia & Ventilation",
    origin: "Germany",
    originFlag: "🇩🇪",
    moq: "5 units",
    leadTime: "10–14 weeks",
    blurb: "German-engineered critical-care ventilation and anesthesia systems.",
    description:
      "Dräger is a global authority in critical-care ventilation and anesthesia workstations, trusted across intensive care and operating theatres. A mission-critical capital line with stringent compliance and careful handling needs.",
    highlights: ["Critical-care grade", "Trusted ICU/OR brand", "Stringent compliance"],
    accent: "#003a5d",
    certifications: ["CE (MDR)", "ISO 13485", "FDA"],
    containerLoad: "Palletized, LCL/FCL",
  },
  {
    slug: "medtronic-surgical-systems",
    name: "Medtronic Surgical Equipment",
    brand: "Medtronic",
    category: "Medical Equipment",
    subcategory: "Surgical Devices",
    origin: "Ireland",
    originFlag: "🇮🇪",
    moq: "10 units",
    leadTime: "8–12 weeks",
    blurb: "World-leading surgical and therapeutic medical device systems.",
    description:
      "Medtronic is the world's largest medical-device company, supplying surgical, energy and therapeutic systems across specialties. A broad, high-value device portfolio requiring careful regulatory documentation for cross-border import.",
    highlights: ["World's #1 device maker", "Broad surgical portfolio", "Regulatory-doc heavy"],
    accent: "#1a1f71",
    certifications: ["CE (MDR)", "ISO 13485", "FDA"],
    containerLoad: "Palletized, LCL/FCL",
  },

  // ─────────────────────────────── Electronics ───────────────────────────────
  {
    slug: "bosch-professional-drill",
    name: "Bosch Professional Cordless Drill",
    brand: "Bosch",
    category: "Electronics",
    subcategory: "Power Tools",
    origin: "Germany",
    originFlag: "🇩🇪",
    moq: "50 units",
    leadTime: "5–7 weeks",
    blurb: "Professional-grade German cordless power tools for trade channels.",
    description:
      "Bosch Professional cordless tools are a global trade-channel standard, built for durability on demanding job sites. A high-velocity SKU for hardware distribution and industrial supply with strong brand pull and battery-platform lock-in.",
    highlights: ["Trade-channel standard", "Durable job-site build", "Battery-platform pull"],
    accent: "#ed0007",
    certifications: ["CE", "RoHS", "WEEE"],
    containerLoad: "2,400 units / 40ft",
  },
  {
    slug: "sony-alpha-camera",
    name: "Sony Alpha Mirrorless Camera",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Audio & Imaging",
    origin: "Japan",
    originFlag: "🇯🇵",
    moq: "40 units",
    leadTime: "5–7 weeks",
    blurb: "Flagship Japanese mirrorless imaging systems for premium retail.",
    description:
      "Sony's Alpha mirrorless line leads the premium imaging market with class-defining sensors and autofocus. A high-ticket consumer-electronics SKU with strong margins and enthusiast demand across specialty and online retail.",
    highlights: ["Class-leading sensors", "High-ticket margins", "Enthusiast demand"],
    accent: "#1a1a1a",
    certifications: ["CE", "RoHS", "FCC"],
    containerLoad: "Palletized, high-value",
  },
  {
    slug: "samsung-qled-tv",
    name: "Samsung QLED Smart TV",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Consumer Electronics",
    origin: "South Korea",
    originFlag: "🇰🇷",
    moq: "1 × 40ft container",
    leadTime: "6–8 weeks",
    blurb: "Quantum-dot smart televisions, a global consumer-electronics leader.",
    description:
      "Samsung QLED televisions combine quantum-dot brightness with a mature smart-TV platform, anchoring the premium display category. A high-volume consumer SKU with seasonal demand spikes and careful palletized container handling.",
    highlights: ["Quantum-dot displays", "Global market leader", "Seasonal volume spikes"],
    accent: "#1428a0",
    certifications: ["CE", "RoHS", "Energy Star"],
    containerLoad: "Palletized by panel size",
  },
  {
    slug: "dyson-cordless-vacuum",
    name: "Dyson Cordless Vacuum",
    brand: "Dyson",
    category: "Electronics",
    subcategory: "Home Appliances",
    origin: "United Kingdom",
    originFlag: "🇬🇧",
    moq: "60 units",
    leadTime: "5–7 weeks",
    blurb: "Premium cordless cleaning technology with strong global brand pull.",
    description:
      "Dyson's cordless vacuums pair high-speed digital motors with engineered filtration, defining the premium home-appliance tier. A high-margin SKU with powerful brand recognition and consistent demand across modern retail and e-commerce.",
    highlights: ["Premium appliance tier", "High-margin SKU", "Powerful brand recognition"],
    accent: "#c9006b",
    certifications: ["CE", "RoHS", "UKCA"],
    containerLoad: "1,500 units / 40ft",
  },
  {
    slug: "bose-noise-cancelling-headphones",
    name: "Bose Noise-Cancelling Headphones",
    brand: "Bose",
    category: "Electronics",
    subcategory: "Audio Systems",
    origin: "United States",
    originFlag: "🇺🇸",
    moq: "80 units",
    leadTime: "5–7 weeks",
    blurb: "Reference-grade noise-cancelling audio for premium retail channels.",
    description:
      "Bose noise-cancelling headphones are a benchmark in personal audio, prized for acoustic quietness and build quality. A compact, high-value SKU that ships densely and turns quickly across electronics and travel-retail channels.",
    highlights: ["Benchmark noise cancelling", "Compact high-value", "Fast retail turnover"],
    accent: "#4a4a4a",
    certifications: ["CE", "RoHS", "FCC"],
    containerLoad: "3,000 units / 40ft",
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

/** Official brand domains — used to fetch each brand's real logo from a logo CDN. */
export const brandDomains: Record<string, string> = {
  Lindt: "lindt.com",
  Barilla: "barilla.com",
  Oreo: "oreo.com",
  Haribo: "haribo.com",
  Twinings: "twinings.co.uk",
  IKEA: "ikea.com",
  "Herman Miller": "hermanmiller.com",
  Vitra: "vitra.com",
  Natuzzi: "natuzzi.com",
  Steelcase: "steelcase.com",
  "Philips Healthcare": "philips.com",
  "Siemens Healthineers": "siemens-healthineers.com",
  "GE HealthCare": "gehealthcare.com",
  Dräger: "draeger.com",
  Medtronic: "medtronic.com",
  Bosch: "bosch.com",
  Sony: "sony.com",
  Samsung: "samsung.com",
  Dyson: "dyson.com",
  Bose: "bose.com",
};

export const categories = [
  "All",
  "FMCG",
  "Furniture",
  "Medical Equipment",
  "Electronics",
] as const;
